VP-4104: Add new data to v3  sample data
VirtoCommerce/vc-sample-data pull request #8
Opened 2020-08-31 07:55 UTC by trueboroda

B2B store FC list is repaired.
Storefront roles permissions was repaired.
Default  B2B demo accounts was added. 
- b2badmin
- b2bemployee
- b2bagent
- Role 'Purchasing agent' for b2b-store
- unnecessary b2b users and contatcts was deleted.

2020-09-01 04:20 UTC, t13ka approved these changes

2020-09-01 05:25 UTC, akak1977 approved these changes

2020-09-01 08:27 UTC, asvishnyakov requested changes
Can't import with latest platform dev and latest modules versions (autoinstalled). Please confirm

2020-09-02 11:19 UTC, trueboroda commented
@asvishnyakov it is not confirmed. On the latest platform with the latest modules, the import was successful.

2020-09-02 11:19 UTC, merged